version: '3.8'
services:
  web:
    image: explabs/vsfi-pixel-battle-web
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 80:80

  api:
    build:
      context: go-api
    container_name: api
    image: explabs/vsfi-pixel-battle-api
    environment:
      - MAX_X=100
      - MAX_Y=100
      - INTERVAL=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379"

#     volumes:
#       - cache:/data

# volumes:
#   cache:
#     driver: local
