version: '3.8'
services:
  web:
    build:
      context: front-end
    container_name: web
    ports:
      - 80:80

  api:
    build:
      context: api
    container_name: api
    environment:
      - MAX_X=100
      - MAX_Y=100
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 5000:5000

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379"

#     volumes:
#       - cache:/data

# volumes:
#   cache:
#     driver: local
