version: '3.8'
services:
  web:
    build:
      context: web
    container_name: web
    ports:
      - 80:3000
  api:
    build:
      context: api
    container_name: api
    ports:
      - 8080:8080
