version: '3.8'
services:
  web:
    build:
      context: front-end
    container_name: web
    ports:
      - 80:80
  api:
    build:
      context: api
    container_name: api
    ports:
      - 5000:5000
