version: '3.8'
services:
  web:
    image: explabs/vsfi-pixel-battle-web
    container_name: web
    ports:
      - 80:3000
  api:
    image: explabs/vsfi-pixel-battle-web
    container_name: api
    ports:
      - 8080:8080
