list_of_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - python3-setuptools
  - rsync

pip_packages:
  - docker 
  - docker-compose