version: "3.9"
services:
  api:
    build:
      context: .
    ports:
      - '5000:5000'
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
